services:
  - type: web
    name: geoshield-osiri
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip \"setuptools<74.0\" wheel Cython && pip install --no-build-isolation -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: geoshield-platform
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip \"setuptools<74.0\" wheel Cython && pip install --no-build-isolation -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0